name: pre-commit

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  terraform-fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Execute terraform fmt -check -recursive .
        run: terraform fmt -check -recursive .
