name: pre-commit

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  terraform-fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: List files
        run: pwd && ls -la

      - name: Execute terraform fmt -check -recursive .
        run: terraform fmt -check -recursive .

      - name: Install pre-commit
        run: |
          sudo apt update
          sudo apt install -y gawk unzip software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install -y python3.7 python3-pip python3-testresources
          pip3 install pre-commit
          curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64.tar.gz")" > terraform-docs.tgz && tar xzf terraform-docs.tgz && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
          curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases/latest | grep -o -E "https://.+?tfsec-linux-amd64")" > tfsec && chmod +x tfsec && sudo mv tfsec /usr/bin/
          ls -la /usr/bin/tfsec
          curl -L "$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz && tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz && sudo mv terrascan /usr/bin/
          python3.7 -m pip install -U checkov

      - name: Pre-commit
        run: pre-commit run -a
